### ISSUE TITLE
files created after 20120731 seem to fail acc. wiki

### ISSUE THREAD

**Issue by roelandjansen** [roelandjansen/pcmos386v501#2] opened 2017-09-05 11:46 UTC
according to https://en.wikipedia.org/wiki/PC-MOS/386

"t appears there is a year 2000 like issue in this product, only happening on 31 July 2012 rather than the year 2000. Files created on the system after this time will no longer work."

This may  need some testing and checks. Maybe issue #1 is also related.

**Comment by andrewbird** [comment] 2017-10-29 17:34
Installation from 1_MOS5userSystemSN0530041410.zip fails if the system date is current. It seems that hdsetup can't read a file it created earlier. Deleting the file it complains about, setting the clock back (I used 1993), and restarting install allows installation to proceed.

**Comment by the-grue** [comment] 2019-01-13 21:00
I have been looking into this particular bug and have made some interesting (though not necessarily related to the problem) observations:

1. 2099 - 1980 = 119 years
2. 1/1/1980 - 7/31/2012 = 11900 days or 1700 weeks
3. 2012 - 1980 = 32 years (rollover to bit position 6)
4. August = 8th month (rollover to bit position 4)

Item 1 is standard DOS, so I don't see that as particularly problematic, though the coincidence of item 2 being 100 x item 1 is interesting.  I just put in the 1700 weeks because the date converter offered that up along with 285600 hours.

I don't think 3 alone causes any problems, or it would have started having issues on 1/1/2012.  Item 4 may or may not be of interest, but I am not ruling it out.

Of course, I expect it is something different completely, or I would have come across the smoking gun already.

I wrote some simple MOS programs and using a FAT reader I wrote years ago on Linux I can see that starting on 8/1/2012 writes to the directories seems to mess up the directory entries and FAT cluster pointers.  You can see the files in a directory listing, you can delete the file, but if you try to open the file it returns "file not found".

@andrewbird to get around the date issue in the installation, I just added "date 08-24-1995" as the first line of autoexec.bat.  (Date chosen as a bit of a joke.)

**Comment by andrewbird** [comment] 2019-01-17 16:31
@the-grue I see you are working on the date problem. I fixed a (maybe) similar thing in dosemu's fat image creation https://github.com/stsp/dosemu2/pull/759 where the dates after 2012 rolled over to 1980 because the 6 bit year field was assumed to be 5 bits wide. I started looking at PC-MOS for some thing similar, but I'm having trouble creating a bootable $$mos.sys, have you managed to boot a PC or Dosemu with a newly built $$mos.sys?

**Comment by src153** [comment] 2019-01-17 18:22
The PCMOS386-9-user.img in IMAGES boots from floppy. Then I built the kernel $$MOS.SYS from source, copied it to floppy, and now it's only the 60 minute demo version. Still boots though.

I floppy booted into MOS with a 1980 date, created a short file "echo abc>z.txt", booted back into DOS 6.22, read the file, all good. Repeated the procedure with a 2019 date, DOS 6..22 can read it, but the contents are garbage. SCANDISK does not complain though, so there is no FAT corruption that SCANDISK understands. There may be some, but SCANDISK knows nothing about it.

I'll have to try looking at the raw bytes with a disk editor.

**Comment by andrewbird** [comment] 2019-01-17 18:57
@src153 Thanks for the confirmation that build works. I realised I'd forgotten to fix the timestamp on it before testing.
Incidentally the problem is in the readpath too. I copied a file on disk outside of MOS, touched it to get the current date, and it's unreadable by MOS.
~~~
[C:\]dir old*.*
 
FILENAME.EXT       SIZE  ----UPDATED---- ATTRB CLS USER  ----CREATED----
 
OLDCMD  .BAT        180   4-07-95   9:13
OLDCMD  .NEW        180   1-16-19  19:19
 
DISKID  DXXXXS MOS          360 BYTES     2 FILES     8,843,264 BYTES REMAINING
 
[C:\]type oldcmd.bat
COPY C:\PCMOS\$$SHELL.OLD C:\$$SHELL.SYS
COPY C:\PCMOS\COMMAND.OLD C:\COMMAND.COM
COPY C:\PCMOS\$$SHELL.OLD C:\PCMOS\$$SHELL.SYS
COPY C:\PCMOS\COMMAND.OLD C:\PCMOS\COMMAND.COM
 
[C:\]type oldcmd.new
Cannot find file
~~~

**Comment by the-grue** [comment] 2019-01-17 20:03
Yeah, I have been down that path already and I am currently looking into the int 38h/int d4h and how MOS stores the user and class information on disk.  Based on what I see of the data structures, they may have used a formerly reserved section of the directory entry to store this information (10 bytes between attribute and update time).  Later versions of DOS use this area for creation time/date, last access date, etc.

I believe the file unreadability may have something to do with the class entry and the security features, but I haven't gotten a good enough understanding yet of how all that works.  Or why it would suddenly start on 8/1/2012.

You'll notice the problem when you see garbage under the CLS and USER fields in a directory listing under MOS for files created after 8/1/2012 OR files created under newer DOS/Windows/Linux/etc.

As for the 5 bit vs 7 bit year, I thought of this and put it aside figuring it would have manifested on 1/1/2012.  Unless it is a combination of year and month somehow clobbering something.

Which gives me an idea!!!

Back in a bit.

**Comment by the-grue** [comment] 2019-01-17 21:33
Well, my hunch didn't pan out.  Looks like MSDOS formatted filesystems and MOS formatted filesystems don't behave any different.

Here's an example of a dump of two different files and their contents.  TEST.TXT is dated 08/01/2012 and TEST2.TXT is dated 01/17/2002.  Both have the same contents, notice the first block for TEST.TXT is garbage and the second one is fine.

0023000   T   E   S   T                   T   X   T      \0  \0  \0  \0
0023020  \0  \0 227   b   1   N 227   b   1   N 002  \0 023  \0  \0  \0
0023040   T   E   S   T   2               T   X   T      \0  \0  \0  \0
0023060  \0  \0 274   b   1   , 274   b   1   , 003  \0 023  \0  \0  \0
0023100  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0
*
0041000 020 303 310 312 345 023 315 350 026 330 030 355 337 356 360 037
0041020 036 374 372 366 366 366 366 366 366 366 366 366 366 366 366 366
0041040 366 366 366 366 366 366 366 366 366 366 366 366 366 366 366 366
*
0042000   "   T   h   i   s       i   s       a       t   e   s   t   "
0042020      \r  \n 366 366 366 366 366 366 366 366 366 366 366 366 366
0042040 366 366 366 366 366 366 366 366 366 366 366 366 366 366 366 366

**Comment by src153** [comment] 2019-01-21 23:50
Working backwards from the error message, I've folllowed the trail to mosfun3d in mosfun39.asm. I see it makes a call to hl_open. I've not looked at that yet, but I'm guessing there's no obvious problem, or you would have already found it.

Single step debugging starting with the call to hl_open would be nice. I wonder if there is a way to serial port debug it with vmware. What have you tried? Any suggestions?

**Comment by roelandjansen** [comment] 2019-01-22 09:54
to be honest, I never ever tried that nor thought about it.

It seems that workstation can do at least with version 5.5 and now that we're at 15.xx I blindly assume it still works this way.

I only googled, not read much since I'm at a short break before I continue working:

https://www.vmware.com/support/ws55/doc/ws_devices_serial_advanced_example_debugging.html
https://briolidz.wordpress.com/2012/03/28/windows-driver-debugging-with-windbg-and-vmware/

**Comment by roelandjansen** [comment] 2019-01-22 09:54
good work so far by the way!

**Comment by src153** [comment] 2019-01-22 15:00
VMWARE debugging sounds like it uses the tools included with the guest, like the Windows kernel debugger or GDB for linux. DOS has no such debugger that I know of. Does PC-MOS? In one of the ASM source files I saw some mention of debugging, but not sure what that's about. Maybe you know more. And there is Softice for DOS but I don't know if it works with a kernel or not.

The PC-MOS kernel makefile builds each ASM like so:

```
public $<
masm $*
del $*.pub

```
I suspect public was a periscope debugger utility. But I don't know what the purpose was, because removing it makes no difference in the object produced by masm.

Meanwhile, I found the Bochs project. It has its own internal debugger, with a GUI interface on a Windows host. I think I will try that first.

**Comment by roelandjansen** [comment] 2019-01-22 15:32
if mem serves right, it indeed was a hw periscope debugger.

**Comment by src153** [comment] 2019-01-22 19:37
Before learning Bochs debugger, which is a sub project in itself, I need to read more code to have a better idea where to focus.

hl_open is not very big, I don't suspect the problem is there. But it calls pathfind in mosfutil.asm, which is not so simple. There is also pathcomp, findnm, and nextnm. A lot of code where things could go wrong.

If you could just compile it like a user app and throw it in Turbo Debugger, it would be much easier. With the Bochs debugger, you have no symbolic names for variables. You have to step line by line and look at the reverse assembled instructions to match them up with where you are in the source code.

The plan of attack is to step through the code with an old date where it succeeds, and then repeat with a current date where it fails. Where they diverge, that's where things go wrong, and then you try to understand why, by looking at registers and variables.

This could take some time.

**Comment by src153** [comment] 2019-01-22 20:05
PC-MOS does have a DEBUG command. I suppose I could write a short ASM program which opens a file, and start it from DEBUG. I guess it would trace into the kernel. That would be as good as using Bochs, since either way, there are no symbolic variable names.

Anyone with better ideas, please enlighten.

**Comment by the-grue** [comment] 2019-01-22 21:12
debug has worked for me so far.  It has been a slow manual process, as you have seen.  Single step, compare where the jumps go, what variables are being referred to, etc in the source files and move on.  I am refreshing my memory on how td works so I can use that or cv to do debugging within MOS.  It would be cool if we could somehow tie the code files used in the kernel to an active debug session within the OS, but I am not aware how to do that.

My guess is that this is how the Periscope debugger was used.  Some of the tools in /bin have periscope banners, such as public and ts.  From what I have read of periscope, it was an actual card you put in the computer to do debugging and there were associated code tools, but that's about all I have found on that subject.

**Comment by sub205** [comment] 2019-01-24 16:48
Strange behaviour, even a disk-image written by windows with 1999 timestamps refuses to work.
Any way to get around this?

I bootet from the img, wrote the 2 disks to images (not bootable) after forcing timestamps to 1999, but even this is not working for me.

**Comment by src153** [comment] 2019-01-24 17:05
I don't understand. Can you provide more context, and details?

**Comment by sub205** [comment] 2019-01-24 17:09
Bootet PCem with PCMOS386-9-user.img as DriveA image.
Created a floppy image with the files of 1_MOS5userSystemSN0530041410.zip.
Did not work as, because files on diskimage got current date (modified).
Changed all timestamps to 01/24/1999 and rewrote image, still same problem.
Systemdate was 01/01/1999.

What is the correct way of creating the images/floppies to install PCMOS with the 2012-bug?

**Comment by sub205** [comment] 2019-01-24 17:16
tried something else, still fails.

mkfs.msdos -C PCMOS1.img 1440
mount PCMOS1.img g -o loop

unzipped 1_MOS5usersystem.zip into it
unmount
loaded image in PCem



![floppy](https://user-images.githubusercontent.com/13260749/51695763-20936780-2004-11e9-9ff7-5dfab715660a.PNG)

**Comment by src153** [comment] 2019-01-24 18:00
I did not use linux or DOSEMU for this, so I can't analyze what you posted. What I did was:

I got the PCMOS386-9-user.img onto a DOS 6.22 real hardware computer, and copied that image onto floppy. DOS 6.22 does not have a diskcopy command, but Norton Commander can do it, so I use that.

Linux DD should also work, for copying the image to floppy.

Then I deleted all the files from the floppy, leaving myself with a bootable floppy. Then I copied the system disk files from SHIPMOS onto the floppy. Then I used a 2nd floppy and copied auxfiles.exe to it. DO NOT expand that file, PC-MOS install does it automatically during the install.

I think there is some official way to create a bootable system floppy, but I did not spend time learning it, so I improvised as above.

As for booting on PCem, I don't know enough about it to help. There is also the Bochs project if you want to try that.

**Comment by src153** [comment] 2019-01-24 18:05
Huh, I just looked in my DOS 6.22 directory and there is a DISKCOPY command. I never knew.

**Comment by the-grue** [comment] 2019-01-24 19:00
Yep, it sure does.  Google VFAT or FAT32 and you will see how MS used some of the 10 reserved bytes in the directory entry that clobber stuff TSL took for their user/class playground.  Also, some entries may be incompatible with later versions of DOS.  Then there's the class byte, which I believe does something with on-disk encryption, but haven't zeroed in on that yet.  Lots of stuff I am sifting through to try to find the root of the 2012 bug.

This is one reason why I am focusing on my DOS 5 based build environments at the moment instead of using 6.22 or Windows 3.1 or Windows 95/98.

**Comment by src153** [comment] 2019-01-24 19:33
BTW, it's well tested, I use it often. It only supports FAT16, not FAT12. The regular DOS defrag can handle FAT12. I wrote it because my FAT16 partition is so big, DOS defrag runs out of memory and quits. Mine does not defrag files, only directories. It also sorts the names to put them in alphabetical order.

**Comment by the-grue** [comment] 2019-01-25 02:32
> I will be glad to share the source freely.

I'll take a copy.  My e-mail is in the git log.

**Comment by the-grue** [comment] 2019-01-25 02:34
On the topic of classes and encryption:

MOS-D191 Page 9-19 "Security"
Precautions for Security Users

When you invoke security, every **file having a non-blank class is stored in an encrypted state**.

This manual is already paying for itself.

**Comment by src153** [comment] 2019-01-25 05:21
> > I will be glad to share the source freely.
> I'll take a copy. My e-mail is in the git log.

I looked at commits but did not see it. I've not cloned a repo, so maybe it's not accessible to me. But it's not a big file, I will post it for all:

[df.zip](https://github.com/roelandjansen/pcmos386v501/files/2794731/df.zip)

**Comment by src153** [comment] 2019-01-25 15:11
DOS directories need defragging because:

a) Deleted directory entries leave empty slots in the list

b) Directories can span multiple clusters, just like files. When a directory contains more than 1,024 entries (may vary, but 1,024 is typical of FAT16), it spans multiple clusters. If you delete many files, the directory becomes inefficient. The multiple clusters should be compacted.

The code that does the compacting updates the FAT cluster chain and prunes the list. Can this be corrupted if killed in progress? I don't remember! I would have to audit the code again, to know for sure.

It's unusual for a directory to have that many entries, so the danger is minimal, but I mention it to forewarn. In my own setup, I don't worry about it, because I can quickly recreate my entire DOS partition by booting into linux and using rsync to copy the files from my server. If you don't have a similar recovery capability, don't rely on my code, I only wrote it for my use, and the documentation is very sparse.

**Comment by src153** [comment] 2019-01-25 22:51
After looking at the code again, the comment about DIX confused even me, and I wrote it. So after studying the code for a while, I improved the comment to explain what's going on:
`
DIX  = directory nodelist exchange, A and B file names are tied to
           dir0 and dir1 file handles, which are swapped when changing
           levels in the breadth first directory search; A=dir1 B=dir0
           which sounds backwards, but 0 is always input and 1 is always
           output (like C std handles); at root level there is no input,
           only output; and since naturally, A comes before B, we start
           with A instead of B; using these different symbols for file
           names vs file handles highlights their difference and makes
           the code less confusing; the file handles dir0 and dir1 are
           swapped when moving down a level, which means the output at
           the current level becomes input to the next level down, and
           so on, until the search is complete
`
Once you have that big picture, the rest of the code is not hard.

**Comment by src153** [comment] 2019-01-26 22:22
@the-grue I will look for the date bug, but I'm not confident that I can find it. With so much ASM code, there are so many things that can go wrong, in so many ways, in so many places, it may never be found.

DEBUG is a little too spartan and tedious for me. So I'm trying to learn Bochs internal debugger in the hope it might speed things along. Bochs looks interesting, because it stops at the first BIOS instruction, letting you set a breakpoint on the first MBR instruction and step through everything. Not that I want to do all that, my plan is to get maximum results with minimal effort. No heavy lifting for me!

What got my attention about Bochs is, you can insert a special dummy instruction in your source code

`xchg bx, bx`

And the Bochs debugger will automatically break there. No searching for an address where you want to set a breakpoint. Just modify the source, rebuild, start the debugger, and wait for your magic breakpoint. So I may be a while, just learning Bochs, before I ever get to the date bug. Don't let me distract you from pursuing it.

**Comment by the-grue** [comment] 2019-01-27 00:16
Thanks for the assist!  I'll be back on it once I get the scanning and code audit done and upload everything.

**Comment by src153** [comment] 2019-01-27 15:59
It didn't take as long as I feared to get started with Bochs debugger. My understanding of it is still very limited, but right now I'm looking at a breakpoint in mosfun39.asm hl_open(), at the statement
`mov [clvl],cl`
Of course Bochs only shows the disassembly of that, but it's not hard to associate with the source code once you have your breakpoint as a starting reference.

Bochs says the call the pathfind returned a value of 3 in the CL register. Not sure what that means just yet, but I've got the tools working. Bochs can boot from a VMWARE 4.x .vmdk file, as they claim.

**Comment by src153** [comment] 2019-01-27 20:45
OK, you want to look at mosfutl4.asm, function optnfile(), label openf1a. This is where the path of success vs failure diverges. The comment says "must have at least exec access to file".

And the comment immediately before that that says, "file access level restricted to lesser of file class access and cumulative access to parent directory". What all that means is not clear to me yet, or why a current date would mess it up, but that's where things go wrong.

Maybe we're getting warm.

**Comment by the-grue** [comment] 2019-01-27 21:31
The class setting controls encryption of the file and also controls security as far as accessing a file.  You seem to be coming to the same conclusion I am.  What is causing dates after 7/31/2012 to start clobbering the class byte and/or user bytes in the directory entries and thereby causing the files to end up encrypted and unreadable?  I believe we are on the right track.  Can't wait to get back to it!

**Comment by sub205** [comment] 2019-01-28 08:35
2011-1980 = 31 = 0b011111
2012-1980 = 32 = 0b100000
When you look at the FAT date format, you see, there are 4 bits.
2012 = 0b00100000 (bit 9-15)
7 = 0b111  (bit 5-8)
31 = 0b11111 (bit 0-4)

0-4
2011-07-31 = 0b0011111 0111 11111
2012-07-30 = 0b0100000 0111 11110
2012-07-31 = 0b0100000 0111 11111
2012-08-01 = 0b0100000  1000 00001

As this is a word, most probably there is some bitshifting and 8bit register stuff going on.
The 2012-08-01 is the higher byte and thus changes from 0b0100000 to 0b0100001

**Comment by src153** [comment] 2019-01-28 16:15
> 2011-1980 = 31 = 0b011111
> 2012-1980 = 32 = 0b100000
> When you look at the FAT date format, you see, there are 4 bits.

4 bits?

> 2012 = 0b00100000 (bit 9-15)

Bits 9 -15 for the year is corrrect, as Duncan Advanced MSDOS page 185 says. but your value is wrong, it's right shifted by 1

But that's beside the point. A 7 bit year allows up to 2107 using 1980 as the base date. 2012 does not overflow the 7 bit field. The values of 31 -> 32 are curious, but since 2012 does not overflow the 7 bit field, it should not be a problem.

Unless there is a bug. Which there is. Good luck finding it.

**Comment by sub205** [comment] 2019-01-28 16:49
sorry about the 4 bit, rewrote my post and didn't check everything afterwards.

Wehen i subtract the basedate (1980) from 2012 i get 32.
This is 0b10 0000 - a overflow from 5 to 6 bits total. Until 2012, the 6th bit was 0 everytime.
And 31-07 is also an overflow from 11111111 to 100000001 (8bit to 9bit)

I tested it with a disk editor under MSDOS 6.22:

FF 40 = 31-07-2012 (0b0100 0000 1111 1111)
01 41 = 1-08-2012 (0b0100 0001 0000 0001)

**Comment by src153** [comment] 2019-01-30 03:20
I used a disk editor and didn't see anything getting clobbered in the FAT directory entry.

In openfile (mosfutl4.asm), which is called by hl_open (mosfun39.asm):
`
  ah = cumulative dir class access level for tcb
  al = access desired
`
In both cases, success vs failure, al = 40h. Those bits are documented in hl_open, they're just the desired file open access bits, no mystery there.

But ah has different values for success vs failure.
  success = 14h
  failure   = 13h

As the user manual says, the cumulative access is the most restrictive one in the path. In my testing, the only directory in the path is root. I don't yet know the bit map for the cumulative access byte, but this is where the problem is. If you know more about it, please advise.

**Comment by src153** [comment] 2019-01-30 17:03
Oops never mind that, I was confused by the location of my breakpoint. In both cases ah = 03h on entry to openfile. It's further along where they differ. Back to the debugger ...

**Comment by src153** [comment] 2019-01-30 20:01
In mosfutl4.asm, below label openf3, I see

```
mov al,[gfbclass] ; class for file
call classlvl
```

The success case moves 00h into al
The failure case moves 41h (ascii 'A') into al

It comes from gfbclass, so somehow, gfbclass get a bogus value in the failure case.

That's all I know ATM, but I'm working backwards, slowly, toward the cause. I hope.

**Comment by the-grue** [comment] 2019-01-30 20:03
I found it!  Well, at least I think I did!  The change I made seems to be working now!  Still doing some testing...

![screenshot from 2019-01-30 12-01-41](https://user-images.githubusercontent.com/3101080/52009073-ddfbe000-2486-11e9-9809-7d266cde8c7a.png)

**Comment by src153** [comment] 2019-01-30 20:05
So what is the fix?

**Comment by the-grue** [comment] 2019-01-30 20:15
> In mosfutl4.asm, below label openf3, I see

You are on the same track as me and a few steps behind.  The bug is a little farther down in the file in the makegfb function.  In summary, they read the file date into AX then clear al, copy the class into al, and do a comparison against ah!  The bit shift in ah with the year in combination to the shift into ah by the high bit of the month causes it to match a class and in turn enable encryption of the files and security so you can't access the file anymore.  It shouldn't be checking against ah since the class is in al, so I modified it to clear AX and copy the class into ah as it appears was intended.  Here's a diff:

@@ -1275,8 +1275,8 @@ mgx1:
 ; systems will modified the class bits, if not 'A' - 'Z' range
 ; mark file with null class
 
-       xor     al,al                   ; default to space
-       mov     al,byte ptr [si+dbbbuf+dclass0]
+       xor     ax,ax                   ; default to space^M
+       mov     ah,byte ptr [si+dbbbuf+dclass0]^M
        cmp     ah,'A'
        jb      mgfbc1
        cmp     ah,'Z'

Care to add the change, build, and help test?  I'll put up a patch for the file.

**Comment by the-grue** [comment] 2019-01-30 20:39
Just rebuilt the software with today's date and everything is still working fine.

I pushed a patch from my fix2012bug branch that applies the changes to all copies of MOSFUTL4.ASM across the repo.

We need more testing though...

**Comment by src153** [comment] 2019-01-30 20:57
Before testing, I will look at the code. Moving the date into AX and the class into AL makes no sense. I want to know more about it. What's a GFB?

**Comment by the-grue** [comment] 2019-01-30 21:11
Global file block.  It is defined in MOSGFB.INC.  When you look at the code, just above my change, you'll see that the date is copied from the dbbbuf into AX and then from AX into the gfbdate.  The last value stored in AX prior to the class stuff is the date in directory format.

        mov     ax,word ptr [si+dbbbuf+ddate]  ; file date
        mov     [gfbdate],ax

But I wouldn't expect less, as far as wanting to look over the code before accepting it.  Look it over, make sure you understand it, and let me know if you have any questions.

I had pretty much given up on the debugger and was grepping and reading code files to track it down.  I used the debugger to write small programs and test all of the date/time related functions to rule them out.  After that, it would only crash or hang my system when I tried to single step through the kernel.

**Comment by src153** [comment] 2019-01-30 22:45
I need a little time. This bug went unfixed for a year. No need to rush it. Unless the world ends tomorrow. And then it's moot.

I grep and read too, to get started. But without seeing the data and code at the same time, in a debugger, the job is harder than it needs to be. Of course with DEBUG it's still hard. That's why I looked for something better. Bochs debugger is the answer. I can start two instances at the same time, using two identical .vmdk files, and I have a magic breakpoint in the code where I want it to stop. Once there, I step each instance one line at a time, keeping them in sync, looking for a divergent code path or different data in the registers. It helps me focus on the problem quickly, like a binary search.

I don't know how far behind you I was, but it was only a matter of time. And I've only been looking at this a few days. Bochs debugger for Windows (the GUI version). Highly recommended.

**Comment by the-grue** [comment] 2019-01-30 22:51
If you want, throw an int 3 breakpoint into the code right above the change I made and see what it does.  Or what you said was the bochs breakpoint, that would probably work better.

**Comment by src153** [comment] 2019-01-30 22:54
Yes I will do that. I may not be smart, but I use smart tools.

**Comment by the-grue** [comment] 2019-01-30 22:58
I have had success rebuilding everything and am moving on to testing tools and applications.  Maybe even Windows.  I saw mention of Windows 3 in the source code and I have the disks floating around here somewhere...

**Comment by src153** [comment] 2019-01-30 23:19
No need for props. It was the tools, not me. I'm not in this for praise, friends, or any other psychological reasons. I just enjoy the code and its discovery. And as I said earlier, this project goes NOWHERE until the date bug is fixed. So that's my motivation.

Speaking of smart tools, I looked at the man page for git and it says "git - the stupid content tracker". I realize the idea of git is to track content and not containers, but if that means you lose original file dates from a DOS archive, I may run a parallel SVN just to make myself happy. And I don't know much about SVN either. I have a lot to learn.

**Comment by src153** [comment] 2019-01-31 02:04
>  The bit shift in ah with the year in combination to the shift into ah by the high bit of the month causes it to match a class and in turn enable encryption of the files and security so you can't access the file anymore

The patch is only two lines. I was looking everywhere for a "bit shift", then I realized you mean the data, which takes on "shifted" values due to the advanced date. Got it. Translating programmer code-think into English is not easy, I understand. That's why documentation is sometimes lacking.

The first time I read your post, I felt dizzy. But now that I understand, the patch sounds correct. However, I want to verify it, by playing around with the failure vs success bit patterns and walking them through the code. But that's just for my amusement, and it may take a while, so don't wait for my vote, if you're satisfied with the patch.

**Comment by the-grue** [comment] 2019-01-31 16:55
@roelandjansen do we feel this can be closed or would you like to have a binary patch for the "as shipped" $$MOS.SYS?

**Comment by sub205** [comment] 2019-01-31 17:01
A binary patch is always a good idea to help other people getting started with a project. The $$MOS.SYS we've got in the repo is broken, so why not fix it?

We have an image for "quick start" (PCMOS386-9-user.img and the other ZIPs) - a patch there would lower the bar for everyone.

**Comment by src153** [comment] 2019-01-31 17:21
The 9 user image boots, but it has the sizes of $$shell.sys vs command.com reversed, as compared to the 5 user image from SHIPMOS. It also has no auxiliary disk, which is strange. Until we understand why, it would be better to take the 5 user SHIPMOS 2 disk file directories and make them into bootable images to help people get started.

**Comment by src153** [comment] 2019-01-31 17:38
@the-grue Your "Code Audit against v5.01 distribution disks"

Does "distribution disks" mean SHIPMOS? I never thought to ask before. Or maybe I did, and forgot.

**Comment by src153** [comment] 2019-01-31 17:50
> lower the bar for everyone

Talk about a big job. The main project directory, and especially SOURCES/src, now that it has two brand new directories, is a bewildering mess. I kind of know my way around now, but somebody looking at it for the first time will not.

If I had my way, I would take the whole project and put it an ARCHIVE directory, leaving the project root empty except for the ARCHIVE direcotry. Then, as the finished pieces become available for acutal use, put them in the root direcotry which is now clean and easy to navigate.

Talk about a big job. You can say that again, heh.

**Comment by sub205** [comment] 2019-01-31 17:55
That's a good point!
First thing would be a diff of the 5 different sourcetrees, then sticking to one and rebuilding a tidy root with it.

Does anyone know right now what they are about?

**Comment by sub205** [comment] 2019-01-31 17:59
BTW: at some point we should rename this repo or just create a new one, because the name itself implies version 5.01.

**Comment by src153** [comment] 2019-01-31 18:05
@the-grue has already created "mos501src" and "latest" which are basically 501 and 502, which indicates where they originated: kernel vs mos5src. However that does account for all the other stuff outside the kernel, which is yet to be tested and understood.

So trying to clean all that up and lower the bar, is a long term job.

**Comment by the-grue** [comment] 2019-01-31 18:51
Yes, that is correct.  We could move jim, mossrc1, mossrc2, and mos5src to an archive directory.  The rest of the code directories would need to be merged into the latest tree along with appropriate build scripts.

**Comment by the-grue** [comment] 2019-01-31 18:58
> A binary patch is always a good idea to help other people getting started with a project. The $$MOS.SYS we've got in the repo is broken, so why not fix it?
> 
> We have an image for "quick start" (PCMOS386-9-user.img and the other ZIPs) - a patch there would lower the bar for everyone.

I started with the 9 user image and will follow up with the other ones.  Added branch binpatch2012 to my repo to track it, but here is the .img file for testing (forced to zip it, github rules):

[PCMOS386-9-user-patched.zip](https://github.com/roelandjansen/pcmos386v501/files/2818670/PCMOS386-9-user-patched.zip)

As suggested in previous posts, I won't do a PR until folks have a chance to test this.

Enjoy!

**Comment by src153** [comment] 2019-01-31 19:16
> would you like to have a binary patch for the "as shipped" $$MOS.SYS?

You've done a lot of work on this project. But if you try to do everything, you'll burn yourself out. People who want things, can put in the effort themselves.

When I muse about how I would do such and such, I'm just thinking out loud. If I really want it done, I will break a sweat and do it. Don't let anyone take advantage of your generosity and willingness to work.

The source is the important thing. If binary images are broken, I don't care. If somebody wants them fixed, let them do the work. Save your strength, energy, and time for the real challenge: source code.

FWIW.

**Comment by src153** [comment] 2019-02-03 03:57
Fixed, closing

**Closed by src153** 2019-02-03 03:57 UTC
